apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: sampledb
        ports:
        - containerPort: 3306
        
# Both volume mounts
        volumeMounts:
        - name: mysql-init-storage
          mountPath: /docker-entrypoint-initdb.d

        - name: mysql-data-storage      # 👈 ADD THIS
          mountPath: /var/lib/mysql     # 👈 VERY IMPORTANT

      volumes:
      - name: mysql-init-storage
        configMap:
          name: mysql-init-script

      - name: mysql-data-storage        # 👈 ADD THIS
        persistentVolumeClaim:
          claimName: mysql-pvc
