apiVersion: v1
kind: Secret
metadata:
  name: app-secret
# 👉 It means generic secret (default type), used to store key-value data without any predefined structure
type: Opaque
data:
  DB_PASSWORD: cm9vdA==
